# Generated by Django 3.0.7 on 2020-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorteners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='ShortenURL',
            new_name='shortURL',
        ),
    ]
