# Generated by Django 3.0.7 on 2020-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorteners', '0006_auto_20200618_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
