# Generated by Django 3.0.7 on 2020-06-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorteners', '0007_link_is_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='_shortURL',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
